app/models.py
# third party imports
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

# Local imports
from app import db, login_manager


class User(UserMixin, db.Model):
	"""
	User model
	"""
	__tablename__ = "user"

	id = db.Column(db.Integer, primary_key = True)
	name = db.Column(db.String(60))
	email = db.Column(db.String(60), unique = True)
	password_hash = db.Column(db.String(128))
	responses = db.relationship("Response", backref = "owner", lazy = "dynamic")

	@property
	def password(self):
		# prevent password from accessing
		raise AttributeError("Password is not a readable attribute")

	@password.setter
	def password(self, password):
		# store password as hashed string
		self.password_hash = generate_password_hash(password)

	def verify_password(self, password):
		# check if hashed password matches actual password
		return check_password_hash(self.password_hash, password)

	def __repr__(self):
		return "<User : {}".format(self.email)


@login_manager.user_loader
def load_user(user_id):
	return User.query.get(int(user_id))


class Response(db.Model):
	"""
	Table for storing a users responses
	"""
	__tablename__ = "response"

	id = db.Column(db.Integer, primary_key = True)
	name = db.Column(db.String(60))
	response1 = db.Column(db.String(60))
	response2 = db.Column(db.String(60))
	response3 = db.Column(db.String(60))
	user_id = db.Column(db.Integer, db.ForeignKey("user.id"))


app/home/forms.py
# Third party imports
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class ResponseForm(FlaskForm):
	"""
	Form to store a user victim's response
	"""
	name = StringField("Enter Your Name", validators=[DataRequired()])
	response1 = StringField("Your crush 1 name", validators=[DataRequired()])
	response2 = StringField("Your crush 2 name", validators=[DataRequired()])
	response3 = StringField("Your crush 3 name", validators=[DataRequired()])
	submit = SubmitField("Analyze")
	

app/__init__.py
# third party imports
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap

# local imports
from config import app_config


# initialization
db = SQLAlchemy()
login_manager = LoginManager()


def create_app(config_name):
	app = Flask(__name__, instance_relative_config = True)
	app.config.from_object(app_config[config_name])
	app.config.from_pyfile("config.py")

	db.init_app(app)

	login_manager.init_app(app)
	login_manager.login_message = "You need to log in to access this page"
	login_manager.login_view = "auth.login"

	Bootstrap(app)

	from app import models

	from .auth import auth as auth_blueprint
	app.register_blueprint(auth_blueprint, url_prefix="/auth")

	from .home import home as home_blueprint
	app.register_blueprint(home_blueprint)

	return app

app/home/__init__.py
# third party imports
from flask import Blueprint

home = Blueprint("home", __name__)

from . import views

app/home/views.py
# third party imports
from flask import render_template, redirect, url_for
from flask_login import login_required

# local imports
from . import home
from app import db
from .forms import ResponseForm
from ..models import User, Response


@home.route("/")
def homepage():
	return render_template("home/index.html")


@home.route("/<int:id>/dashboard")
@login_required
def dashboard(id):
	user = User.query.filter_by(id = int(id)).first()

	# if the given id doesn't belong to anyone, redirect to homepage
	if user is None:
		return redirect(url_for("home.homepage"))

	responses = Response.query.filter_by(owner = user).all()

	return render_template("home/dashboard.html", responses = responses)


@home.route("/<int:id>/analyzer", methods=["GET", "POST"])
def analyzer(id):
	form = ResponseForm()

	# check the given id
	user = User.query.filter_by(id = int(id)).first()
	if user is not None and form.validate_on_submit():
		response = Response(name = form.name.data,
							response1 = form.response1.data,
							response2 = form.response2.data,
							response3 = form.response3.data,
							owner = user)
		db.session.add(response)
		db.session.commit()

		form_submitted = True

		return render_template("home/oops.html", form_submitted = form_submitted, name = user.name)

	return render_template("home/analyze.html", form = form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} {% endblock %} | Love Analyzer</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
	 <nav class="navbar" role="navigation">
        <div class="container topnav">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}">Love<strong>Analyzer</strong></a>
            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('home.dashboard', id=current_user.id) }}">Dashboard</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                        <li><a><i class="fa fa-user"></i> Hi, {{ current_user.name }}!</a></li>
                    {% else %}
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                        <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    {% endif %}
              </ul>
            </div>
        </div>
    </nav>
    <div class="wrapper">
        
      {% block body %}
      {% endblock %}
      
      <div class="push"></div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <ul class="list-inline">
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                        <li class="footer-menu-divider">⋅</li>
                        
                        {% if current_user.is_authenticated %}
                            <li><a href="{{ url_for('home.dashboard', id=current_user.id) }}">Dashboard</a></li>
                            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                        {% else %}
                            <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                            <li class="footer-menu-divider">⋅</li>
                            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>

                <div class="col-md-4 text-right">
                    <p class="copyright small">Copyright © 2017. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

app/templates/home/analyze.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block title %} Discover your true love {% endblock %}

{% block body %}

<div class="container jumbotron">
	<div class="row">
		<div class="col-md-8 center">
			<h1>Discover Your Perfect Match</h1>

			<p>So you think what Artificial Intelligence can do? Think again, what it can't do? We use Artificial Intelligence to find your perfect match.</p>

			<p>All you've to do is provide your name, and name of your 3 whom you love. Leave all the rest to us.</p>
		</div>
	</div>



	<div class="row">
		<div class="col-md-6 center analyze-form">
			{{ utils.flashed_messages() }}

			{{ wtf.quick_form(form) }}
			
		</div>
	</div>
</div>

{% endblock %}

app/templates/home/dashboard.html
{% extends "base.html" %}

{% block title %} Dashboard {% endblock %}

{% block body %}

<div class="row">
	<div class="container">
		<div class="col-lg-12 text-center">
			<h1>Hello, {{ current_user.name }}</h1>
		</div>

		{% if responses %}
			{% for response in responses %}

				<div class="col-sm-4 col-md-3 response">
	                <table class="table table-stripped">
	                    <thead>
	                        <tr>
	                            <th>Friend' Name:</th>
	                            <th>{{ response.name }}</th>
	                        </tr>
	                    </thead>
	                    
	                    <tbody>
	                        <tr>
	                            <th scope="row">Crush 1 Name:</th>
	                            <td>{{ response.response1 }}</td>
	                        </tr>
	                        
	                        <tr>
	                            <th scope="row">Crush 2 Name:</th>
	                            <td>{{ response.response2 }}</td>
	                        </tr>
	                        
	                        <tr>
	                            <th scope="row">Crush 3 Name:</th>
	                            <td>{{ response.response3 }}</td>
	                        </tr>
	                    </tbody>
	                </table>
        		</div>

    		{% endfor %}

			<div class="col-sm-12">
				<p>Share the following url with your friends & loved ones and know on whom they have a crush.</p>
            
	            <code>
	                {{ request.url_root + current_user.id|string + "/analyzer" }}
	            </code>
			</div>

		{% else %}
			<div class="col-lg-12 padded">
				<h2>No one has responded yet, check back later.</h2>
		        <p>Share the following url with your friends & loved ones and know on whom they have a crush.</p>
		        
		        <code>
		            {{ request.url_root + current_user.id|string + "/analyzer" }}
		        </code>
					
			</div>

		{% endif %}

	</div>
</div>
{% endblock %}

app/templates/home/index.html
{% extends "base.html" %}

{% block title %} Welcome to Love Analyzer {% endblock %}

{% block body %}

<div class="container">
	<div class="row">

		<div class="col-md-9 hero center">
			<h1>Want to Know names of your friend's secret crushes?</h1>
			<h2>Trick them into telling you.</h2>

			<div class="col-md-5 actions">
				<p>All you've to do is:</p>

				<ol>
					<li><a href="{{ url_for('auth.register') }}">Create </a> your unique link.</li>
					<li>Share it with your friends.</li>
					<li>Sit back and relax. We'll keep you updated.</li>
				</ol>

				<a href="{{ url_for('auth.register') }}" class="btn btn-lg btn-primary"> Create your free link</a>
			</div>
		</div>

	</div>
</div>

{% endblock %}

app/templates/home/oops.html
{% extends "base.html" %}

{% block title %} Oopss {% endblock %}

{% block body %}

	{% if form_submitted %}
		<div class="row">
			<div class="container">
				<div class="col-lg-12 padded">
					<h1>Oops</h1>
					<h2>We are sorry, but your responses has been sent to <strong>{{ name }}</strong></h2>
					<p><a href="{{ url_for('auth.register') }}" class="btn btn-default">Create a free account</a> and know your friends secrets.</p>
				</div>
			</div>
		</div>
	{% else %}
		{{ render_template(url_for("home.homepage")) }}
	{% endif %}

{% endblock %}